SAMPLES: 
  - child
  - father
  - mother


FASTQ_DIR: "/omaha-beach/hlemoine/fastq"


HG19_PATH: "/groups/bgc/hg19/refseq/hg19_from2bit.fa "

 #? "/data/bio-databases/hg19_UCSC/bwa_index/hg19" # Alignment
# REF: "/data/bio-databases/hg19_UCSC/ucsc.hg19.fasta" # Ref
# DICT: "/data/bio-databases/hg19_UCSC/ucsc.hg19.dict" # Sort Freebayes
# DBSNP: "/data/bio-databases/hg19_Bundle_GATK/dbsnp_138.hg19.vcf" # Base Recalibration / Haplotype Caller
# GOLDINDEL: "/data/bio-databases/hg19_Bundle_GATK/Mills_and_1000G_gold_standard.indels.hg19.vcf" # Base Recalibration

# REFSEQ: "/data/bio-databases/BedFiles/RefSeq_UCSC_Exons_hg19_padded100.bed" # BED for Variant Calling

# DBSNPEFF: ""