#Samples
SAMPLES: 
  - mother
  - father

#Directories
# FASTQ_DIR: "/omaha-beach/hlemoine/fastq"
 
FASTQ_DIR: "/home/genouest/bgc/hlemoine/project/solidsnake/datatest"


#Databases
HG19_PATH: "/omaha-beach/hlemoine/databases/hg19_UCSC/ucsc.hg19.fasta"
HG19_DICT_PATH: "/omaha-beach/hlemoine/databases/hg19_UCSC/ucsc.hg19.dict"
GOLDINDEL_PATH: "/omaha-beach/hlemoine/databases/bundle_GATK/Mills_and_1000G_gold_standard.indels.hg19.vcf"
DBSNP_PATH: "/omaha-beach/hlemoine/databases/bundle_GATK/dbsnp_138.hg19.vcf"
REFSEQ_PATH: "/omaha-beach/hlemoine/databases/bedfiles/RefSeq_UCSC_Exons_hg19_padded50.bed"
#DBSNPEFF: "/omaha-beach/hlemoine/databases/snpeff/hg19"



#Parameters
JAVA_ARGS: "-Xmx4G"

FREEBAYES:
  MIN_ALTERNATE_QSUM: 40

FILTER:
  HARD_TO_VALIDATE: "MQ0 >= 4 && ((MQ0 / (1.0*DP)) > 0.1)"
  LOW_COVERAGE: "DP < 5"
  VERY_LOW_QUAL: "QUAL < 30.0"
  LOW_QUAL: "QUAL > 30.0 && QUAL < 50.0"
  LOW_QD: "QD < 1.5"
  FISHER_STRAND_BIAS: "FS > 60.0"

FILTER_SNP:

FILTER_INDEL:
