#Samples
SAMPLES: 
  - father
  - mother

#Directories
FASTQ_DIR: "/omaha-beach/hlemoine/fastq"

#Databases
HG19_PATH: "/omaha-beach/hlemoine/databases/hg19_UCSC/ucsc.hg19.fasta" #Ref
HG19_DICT_PATH: "/omaha-beach/hlemoine/databases/hg19_UCSC/ucsc.hg19.dict" #Sort Freebayes
GOLDINDEL_PATH: "/omaha-beach/hlemoine/databases/bundle_GATK/Mills_and_1000G_gold_standard.indels.hg19.vcf" #Base Recalibration
DBSNP_PATH: "/omaha-beach/hlemoine/databases/bundle_GATK/dbsnp_138.hg19.vcf" #Base Recalibration/Haplotype Caller
REFSEQ_PATH: "/omaha-beach/hlemoine/databases/bedfiles/RefSeq_UCSC_Exons_hg19_padded50.bed" #BED for Variant Calling

#DBSNPEFF: "/omaha-beach/hlemoine/databases/snpeff/hg19"